version: "3.8"

services:
  chatbot-ui:
    build:
      context: ./chatbot
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./chatbot:/app      # Mount your source code
    environment:
      NEXT_PUBLIC_SUPABASE_URL: ${SUPABASE_URL}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      NEXT_PUBLIC_OLLAMA_URL: ${OLLAMA_URL}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
      NEXT_PUBLIC_USER_FILE_SIZE_LIMIT: 10485760
    depends_on:
      # - supabase-db
      - ollama

  # supabase-db:
  #   image: supabase/postgres:15.8.1.100
  #   container_name: supabase-db
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: postgres
  #   ports:
  #     - "54321:5432"
  #   volumes:
  #     - supabase-db-data:/var/lib/postgresql/data
  
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped

volumes:
  # supabase-db-data:
  ollama-data:
