version: "3.8"

services:
  chatbot-ui:
    build:
      context: ./chatbot
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./chatbot:/app      # Mount your source code
      - /app/node_modules   # Prevent overwriting node_modules
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/chatbot?schema=public"
      NEXTAUTH_URL: "http://localhost:3000"
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXT_PUBLIC_OLLAMA_URL: ${OLLAMA_URL}
      NEXT_PUBLIC_USER_FILE_SIZE_LIMIT: 10485760
    depends_on:
      - postgres
      - ollama

  postgres:
    image: postgres:15
    container_name: chatbot-postgres-dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatbot
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
      - ./chatbot/scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: unless-stopped
  
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped

volumes:
  postgres-dev-data:
  ollama-data:
