version: "3.8"

services:
  chatbot-ui:
    build: ./chatbot
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/chatbot?schema=public"
      NEXTAUTH_URL: "http://localhost:3000"
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXT_PUBLIC_OLLAMA_URL: ${OLLAMA_URL}
      NEXT_PUBLIC_USER_FILE_SIZE_LIMIT: 10485760
    depends_on:
      - postgres
      - ollama

  postgres:
    image: postgres:15
    container_name: chatbot-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatbot
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
  
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped

volumes:
  postgres-data:
  ollama-data:
